data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz
  raw_data_path: raw_data
  downloaded_zip_file_path: tgz_data
  ingested_dir: ingested_data
  train_data_dir: train
  test_data_dir: test

data_validation_config:
  schema_file_path: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html

data_transformation_config:
  add_bedroom_per_room: true
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  processed_data_path: preprocessed
  preprocessed_object_file_name: preprocessed.pkl

model_trainer_config:
  trained_model_file_path: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.8
  model_config_dir: config
  model_config_file_name: model.yaml

model_evaluation_config:
  model_evaluation_file_name: model_evaluation.yaml
  
model_pusher_config:
  model_export_dir_path: saved_models

training_pipeline_config:
  pipeline_name: house_price_prediction
  artifact_dir: artifact